name: down_yt
description: a youtube downloader application
version: 0.0.1-alpha
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.6

dependencies:
  # Android Path
  android_path_provider: ^0.3.0

  # Notification Manager
  awesome_notifications: ^0.7.4+1

  # Dart State Management
  bloc: ^8.1.0

  # Built List
  built_collection: ^5.1.1

  # HTTP Requests
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  # Functional Programming
  dartz: ^0.10.1

  # Equal data and type
  equatable: ^2.0.5

  # Flutter SDK
  flutter:
    sdk: flutter

  # Flutter State Management
  flutter_bloc: ^8.1.1

  # Video Encoding and Rendering
  ffmpeg_kit_flutter: ^5.1.0

  # Localization(Language and types)
  flutter_localizations:
    sdk: flutter

  # flutter_vlc_player: ^7.1.5
  # State Management
  get_it: ^7.2.0

# Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Checks internet Connections
  internet_connection_checker: ^0.0.1+3

  # International Localization
  intl: ^0.17.0



  # Mini Player
  miniplayer: ^1.0.1

  # Open File
  open_file: ^3.2.1

  # Gets the paths
  path_provider: ^2.0.11

  # Gets Permissions on Android devices
  permission_handler: ^10.0.0
  pip_view: ^0.9.7
  piped_api:
    git:
      url: https://github.com/TeamPiped/piped_dart
  pod_player: ^0.1.0
  share_plus: ^4.0.8
  # Webview with other features
  webviewx: ^0.2.1

  # Youtube API and Downloadable
  youtube_explode_dart: ^1.12.4

  # Flutter Youtube Player
  # youtube_player_flutter: ^8.1.1

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  #  hive_generator: ^2.0.0
  #  build_runner: ^2.3.2
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
